"""
Tests for `roc-solve-extracted` (`ocaml/r21_extracted_solve.ml`), the
thin adapter around `compute_repair_or_separator` as extracted from Rocq
(`rocq/ExtractR21.v`, regenerated by `make extract-r21`, never
committed -- see that file's own header).

The oracle for every case is NOT "the extracted generator's own opinion
of itself" -- it is: every certificate the extracted generator emits must
be independently ACCEPTed by BOTH existing checkers
(`r21_certificate_checker.py`, `roc-verify-ocaml`). Extraction is judged
by whether its output survives external verification, exactly as the
hand-written generator already is.

Two comparisons against the existing hand-written Python generator
(`r21_repair_or_separator.py`, via `r21_certificate_emitter.build_
certificate`), used deliberately differently:

  - PARITY (witness identity): for a determinate system (a square,
    non-singular `D`, or R1's own four-cycle), both generators implement
    the same algorithm (Gauss-Jordan elimination with the same top-to-
    bottom pivot selection), so they are expected to produce the exact
    same witness, and this is asserted directly.
  - SEMANTIC EQUIVALENCE (not witness identity): for an underdetermined
    repairable system, more than one valid repair exists; the two
    generators are not required to agree on which one they return, only
    that each of their outputs independently verifies. Asserting byte
    equality there would be testing an accident of pivot-selection
    order, not a proved property.

Skips (not fails) if `roc-solve-extracted` has not been built
(`make check-r21-extraction`, which itself runs `make extract-r21`
first) -- `make check-all` builds it before running this suite; a plain
`make check-python`/`pytest` without the Rocq+OCaml+opam-or-apt
toolchain still passes, skipping this coverage.
"""

import json
import os
import random
import subprocess
import sys
from fractions import Fraction as F
from pathlib import Path

import pytest

from r21_certificate_emitter import build_certificate as python_build_certificate

REPO_ROOT = Path(__file__).resolve().parent.parent
EXTRACTED_BINARY = REPO_ROOT / "roc-solve-extracted"
OCAML_CHECKER = REPO_ROOT / "roc-verify-ocaml"

extraction_missing = pytest.mark.skipif(
    not os.access(EXTRACTED_BINARY, os.X_OK),
    reason="roc-solve-extracted not built; run `make check-r21-extraction` first",
)
ocaml_checker_missing = pytest.mark.skipif(
    not os.access(OCAML_CHECKER, os.X_OK),
    reason="roc-verify-ocaml not built; run `make check-r21-ocaml` first",
)


def to_str_matrix(D):
    return [[str(F(x)) for x in row] for row in D]


def to_str_vector(v):
    return [str(F(x)) for x in v]


def write_input(tmp_path, D, r, name="input.json"):
    path = tmp_path / name
    path.write_text(json.dumps({"schema": "roc-input/v1", "D": to_str_matrix(D), "r": to_str_vector(r)}))
    return path


def run_extracted_solve(input_path, tmp_path):
    cert_path = tmp_path / "extracted_cert.json"
    result = subprocess.run(
        [str(EXTRACTED_BINARY), str(input_path), "--certificate", str(cert_path)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, f"roc-solve-extracted failed: {result.stdout}{result.stderr}"
    return cert_path


def run_python_checker(input_path, cert_path) -> int:
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "r21_certificate_checker.py"), str(input_path), str(cert_path)],
        capture_output=True, text=True,
    )
    return result.returncode


def run_ocaml_checker(input_path, cert_path) -> int:
    result = subprocess.run(
        [str(OCAML_CHECKER), str(input_path), str(cert_path)],
        capture_output=True, text=True,
    )
    return result.returncode


def assert_both_checkers_accept(input_path, cert_path):
    py_rc = run_python_checker(input_path, cert_path)
    assert py_rc == 0, f"Python checker rejected the extracted generator's certificate: {input_path}"
    if os.access(OCAML_CHECKER, os.X_OK):
        oc_rc = run_ocaml_checker(input_path, cert_path)
        assert oc_rc == 0, f"OCaml checker rejected the extracted generator's certificate: {input_path}"


# --------------------------------------------------------------------------
# Core cases: repairable, separator, R1 four-cycle, boundary dimensions,
# rectangular matrices, row swaps, rational pivots, negative coefficients,
# large exact rationals.
# --------------------------------------------------------------------------

CORE_CASES = {
    "simple_repairable": ([[F(1), F(0)], [F(0), F(1)]], [F(3), F(5)]),
    "simple_separator": ([[F(1)], [F(1)]], [F(1), F(0)]),
    "four_cycle": (
        [[F(-1), F(1), F(0), F(0)], [F(0), F(-1), F(1), F(0)], [F(0), F(0), F(-1), F(1)], [F(-1), F(0), F(0), F(1)]],
        [F(1), F(1), F(1), F(-2)],
    ),
    "zero_dimensional": ([], []),
    "minimal_dimensional_separator": ([[], []], [F(5), F(3)]),
    "rectangular_wide": ([[F(1), F(1), F(1)]], [F(6)]),
    "rectangular_tall_inconsistent": ([[F(1), F(0)], [F(0), F(1)], [F(1), F(1)]], [F(1), F(1), F(3)]),
    "requires_row_swap": ([[F(0), F(1)], [F(1), F(0)]], [F(5), F(3)]),
    "requires_rational_pivot": ([[F(3), F(1)], [F(2), F(2)]], [F(5), F(4)]),
    "negative_coefficients": ([[F(-2), F(3)], [F(1), F(-1)]], [F(1), F(1)]),
    "large_exact_rationals": (
        [[F(123456789012345678901234567890), F(0)], [F(0), F(1)]],
        [F(987654321098765432109876543210), F(5)],
    ),
}


@extraction_missing
@pytest.mark.parametrize("name", CORE_CASES.keys())
def test_extracted_generator_certificate_accepted_by_both_checkers(name, tmp_path):
    D, r = CORE_CASES[name]
    input_path = write_input(tmp_path, D, r)
    cert_path = run_extracted_solve(input_path, tmp_path)
    assert_both_checkers_accept(input_path, cert_path)


@extraction_missing
def test_four_cycle_witness_matches_paper_exactly():
    """R1's own canonical witness (README.md/STATUS.md): z=(-1,-1,-1,1),
    pairing -5, normalised -1/5 z = (1/5,1/5,1/5,-1/5). The extracted
    generator must reproduce this exact value, not merely some other
    valid separator -- a determinate system, where witness identity is a
    meaningful check, not an accident of implementation."""
    import tempfile
    D, r = CORE_CASES["four_cycle"]
    with tempfile.TemporaryDirectory() as d:
        tmp_path = Path(d)
        input_path = write_input(tmp_path, D, r)
        cert_path = run_extracted_solve(input_path, tmp_path)
        cert = json.loads(cert_path.read_text())
        assert cert["result"] == "separator"
        assert cert["separator"] == ["1/5", "1/5", "1/5", "-1/5"]


# --------------------------------------------------------------------------
# Parity vs. the hand-written Python generator: witness identity for
# determinate systems, semantic equivalence (not identity) for an
# underdetermined one.
# --------------------------------------------------------------------------

@extraction_missing
@pytest.mark.parametrize("name", ["simple_repairable", "four_cycle", "negative_coefficients", "requires_row_swap", "requires_rational_pivot"])
def test_parity_witness_identity_for_determinate_systems(name, tmp_path):
    D, r = CORE_CASES[name]
    input_path = write_input(tmp_path, D, r)
    cert_path = run_extracted_solve(input_path, tmp_path)
    extracted_cert = json.loads(cert_path.read_text())
    python_cert = python_build_certificate(D, r)
    assert extracted_cert["result"] == python_cert["result"]
    key = extracted_cert["result"]
    assert extracted_cert[key] == python_cert[key], (
        f"{name}: extracted witness {extracted_cert[key]} != Python witness {python_cert[key]} "
        f"for a determinate system, where both algorithms should coincide"
    )


@extraction_missing
def test_semantic_equivalence_not_identity_for_underdetermined_system(tmp_path):
    """D=[[1,1]], r=[3]: b=(3,0) and b=(0,3) (and infinitely many others)
    are all valid repairs. The extracted and Python generators are NOT
    required to pick the same one -- only that each independently
    verifies. This is the deliberate contrast with the parity test above."""
    D = [[F(1), F(1)]]
    r = [F(3)]
    input_path = write_input(tmp_path, D, r)
    cert_path = run_extracted_solve(input_path, tmp_path)
    assert_both_checkers_accept(input_path, cert_path)
    extracted_cert = json.loads(cert_path.read_text())
    python_cert = python_build_certificate(D, r)
    assert extracted_cert["result"] == "repair" == python_cert["result"]
    # No assertion that the witnesses are equal -- see docstring.


# --------------------------------------------------------------------------
# Deterministic random small systems: D and b chosen by a seeded RNG, r
# defined as D@b via a from-scratch computation (not rational_linear_
# algebra.mat_vec, not either checker's own code) -- correct by
# construction, then checked the same way as everything else: both
# checkers must accept the extracted generator's certificate.
# --------------------------------------------------------------------------

def _reference_mat_vec(D, b):
    return [sum((D[i][j] * b[j] for j in range(len(b))), F(0)) for i in range(len(D))]


def _random_small_systems(seed: int, count: int):
    rng = random.Random(seed)
    cases = []
    for _ in range(count):
        m = rng.randint(1, 4)
        n = rng.randint(1, 4)
        D = [[F(rng.randint(-9, 9)) for _ in range(n)] for _ in range(m)]
        b = [F(rng.randint(-9, 9)) for _ in range(n)]
        r = _reference_mat_vec(D, b)
        cases.append((D, r))
    return cases


RANDOM_CASES = _random_small_systems(seed=20260714, count=30)


@extraction_missing
@pytest.mark.parametrize("i,case", list(enumerate(RANDOM_CASES)), ids=[f"random_{i}" for i in range(len(RANDOM_CASES))])
def test_extracted_generator_on_random_systems(i, case, tmp_path):
    D, r = case
    input_path = write_input(tmp_path, D, r)
    cert_path = run_extracted_solve(input_path, tmp_path)
    assert_both_checkers_accept(input_path, cert_path)
